kind: pipeline
type: docker
name: default

steps:
- name: Install S2i
  image: alpine
  volumes:
    - name: docker-socket
      path: /var/run/docker.sock
  commands:
    - wget -O - https://github.com/openshift/source-to-image/releases/download/v1.2.0/source-to-image-v1.2.0-2a579ecd-linux-amd64.tar.gz | tar -xzvf -

- name: BUILD s2i-httpd-24-mkdocs-centos7
  image: alpine
  volumes:
    - name: docker-socket
      path: /var/run/docker.sock
  environment:
    DOCKER_USER:
      from_secret: DOCKER_USER
    DOCKER_TOKEN:
      from_secret: DOCKER_TOKEN
  commands:
    - apk add docker
    - docker build -t s2i-httpd-24-mkdocs-centos7 s2i-httpd-24-mkdocs/
    - docker tag s2i-httpd-24-mkdocs-centos7 getais/s2i-httpd-24-mkdocs-centos7
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - docker push getais/s2i-httpd-24-mkdocs-centos7

- name: BUILD mkdocs-example
  image: alpine
  volumes:
    - name: docker-socket
      path: /var/run/docker.sock
  commands:
    - ./s2i build docs s2i-httpd-24-mkdocs-centos7 mkdocs-example

- name: RUN docker image
  image: docker/compose
  volumes:
    - name: docker-socket
      path: /var/run/docker.sock
  commands:
    - docker-compose up -d --force-recreate


volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock

